---
- name: Prepare localhost to install GrapheneOS on a Pixel 7A
  gather_facts: yes
  gather_subset:
    - "env"
  hosts: localhost

  tasks:
    - name: Setup to Install GrapheneOS
      include_role:
        name: grapheneos
      vars:
        # Phone model - Pixel 7a
        # See https://grapheneos.org/releases
        graphene_img: lynx-factory-2024020500  