---
# Install Pixel7A using platform tools
# TODO: Verify this recipe
- name: add graphene files dir
  ansible.builtin.file:
    path: "{{ graphene_files_dir }}"
    state: directory
# TODO: Add verification
- name: get graphene for Pixel7A
  ansible.builtin.get_url:
    url: https://releases.grapheneos.org/lynx-factory-2024020500.zip
    dest: "{{ graphene_files_dir }}"
- name: get allowed signers
  ansible.builtin.get_url:
    url: https://releases.grapheneos.org/allowed_signers
    dest: "{{ graphene_files_dir }}"
- name: get signature
  ansible.builtin.get_url:
    url: https://releases.grapheneos.org/lynx-factory-2024020500.zip.sig
    dest: "{{ graphene_files_dir }}"
- name: verify the release file
  ansible.builtin.shell:
    cmd: ssh-keygen -Y verify -f allowed_signers -I contact@grapheneos.org -n "factory images" -s DEVICE_NAME-factory-VERSION.zip.sig < DEVICE_NAME-factory-VERSION.zip
    chdir: "{{ graphene_files_dir }}"
- name: unpack Graphene
  ansible.builtin.unarchive:
    src: "{{ graphene_files_dir }}/lynx-factory-2024020500.zip"
    dest: "{{ graphene_files_dir }}"
    remote_src: yes  # local is our remote...neat

