---
# Install Pixel7A using platform tools
- pause:
    prompt: "On your phone, unlock OEM (Developer Settings / OEM unlocking), then boot into the bootloader interface (power+vol down), then press Enter"
- name: unlock for flashing
  ansible.builtin.shell:
    cmd: "fastboot flashing unlock"
  environment:
    PATH: '{{ fastboot_dir }}:{{ ansible_env.PATH }}'
- pause:
    prompt: "Run the following command in a separate terminal:\n"
- name: flash GrapheneOS to Pixel7A
  ansible
  ansible.builtin.shell:
    cmd: "{{ graphene_files_dir }}/{{ graphene_img }}/flash-all.sh"
    chdir: "{{ graphene_files_dir }}/{{ graphene_img }}"
  environment:
    PATH: '{{ fastboot_dir }}:{{ ansible_env.PATH }}'
- name: lock after flashing
  ansible.builtin.shell:
    cmd: "fastboot flashing lock"
- pause:
    prompt: "On your phoe, set the bootloader to locked, then unplug and reboot and enjoy GrpaheneOS."