---
# Install Pixel7A using platform tools
- name: unlock for flashing
  shell: "{{ fastboot_bin }} flashing unlock"
- name: flash GrapheneOS to Pixel7A
  shell: ./flash-all.sh
    chdir: "{{ graphene_files_dir }}/{{ graphene_img }}"

