---
# Install Pixel7A using platform tools
- pause:
    prompt: "On your phone, unlock OEM (Developer Settings / OEM unlocking), then boot into the bootloader interface (power+vol down), then press Enter"
- name: unlock for flashing
  ansible.builtin.shell:
    cmd: "{{ fastboot_bin }} flashing unlock"
- name: flash GrapheneOS to Pixel7A
  ansible.builtin.shell:
    cmd: flash-all.sh
    chdir: "{{ graphene_files_dir }}/{{ graphene_img }}"